#pragma once

#include <iostream>
#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/noise.hpp>
#include <stdlib.h>
#include <vector>
#include <list>
#include <queue> 
#include <map>
#include <cstdlib>
#include <cassert>
#include <stdexcept>
#include <math.h>
#include <cmath>
#include "Metrics.h"
#include "GlobalStructures.h"
#include <functional>
#include "btBulletDynamicsCommon.h"